language: ruby

rvm:
  - 2.0.0

notifications:
  irc: 
    channels:
      - "irc.freenode.org#libtechnyu"
    template:
      - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
      - "Change view : %{compare_url}"
      - "Build details : %{build_url}"
