version: 2
jobs:
  run_tests:
    docker:
      - image: nyulibraries/wtf_sfx
    working_directory: /app
    steps:
      - run:
          name: Run rspec
          command: |
            bundle exec rake
      - store_test_results:
          path: /app/test-results
      - store_artifacts:
          path: /app/test-results

workflows:
  version: 2
  run_hourly:
    triggers:
      - schedule:
          cron: "0 * * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - run_tests
