version: 2
jobs:
  run_tests:
    docker:
      - image: quay.io/nyulibraries/circleci_docker:18.06.1-dc-1.23.2-0
    working_directory: /app
    steps:
      - setup_remote_docker
      - run:
          name: Authenticate Quay
          command: |
            docker login -u "$QUAY_USERNAME" --password "$QUAY_PASSWORD" quay.io
      - run:
          name: Run rspec
          command: |
            docker run --name wtf_sfx quay.io/nyulibraries/wtf_sfx
      - run:
          name: Get Junit tests from stopped container
          when: always
          command: docker cp wtf_sfx:/app/test-results .
      - store_test_results:
          path: /app/test-results
      - store_artifacts:
          path: /app/test-results

workflows:
  version: 2
  build-and-test:
    jobs:
      - run_tests
  run_hourly:
    triggers:
      - schedule:
          cron: "0 * * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - run_tests
