version: 2
jobs:
  run_tests:
    docker:
      - image: circleci/ruby:2.5.1
    working_directory: ~/app
    steps:
      - checkout
      - restore_cache:
          key: phantomjs-2-1-1
      - run:
          name: Install PhantomJS Dependencies
          command: |
            [ -f /usr/local/bin/phantomjs ] || sudo apt-get update
            [ -f /usr/local/bin/phantomjs ] || sudo apt-get install -y fontconfig wget
      - run:
          name: Install PhantomJS
          command: |
            [ -f /usr/local/bin/phantomjs ] || wget -O /tmp/phantomjs.tar.bz2 https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2
            [ -f /usr/local/bin/phantomjs ] || tar -xjf /tmp/phantomjs.tar.bz2 -C /tmp
            [ -f /usr/local/bin/phantomjs ] || sudo mv /tmp/phantomjs-2.1.1-linux-x86_64/bin/phantomjs /usr/local/bin/phantomjs
      - save_cache:
          key: phantomjs-2-1-1
          paths:
            - /usr/local/bin/phantomjs
      - restore_cache:
          keys:
            - wtf_sfx-{{ checksum "Gemfile.lock" }}
            - wtf_sfx-
      - run:
          name: Bundle Install
          command: bundle check || bundle install
      - save_cache:
          key: wtf_sfx-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run:
          name: Run rspec in parallel
          command: |
            bundle exec rake

workflows:
  version: 2
  run_hourly:
    triggers:
      - schedule:
          cron: "0 * * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - run_tests
